### ISSUE TITLE
Error: Invalid or corrupt jarfile InsnCounter.jar

### ISSUE THREAD

**Issue by iSultan** [lvxiaoxin/Java-ByteCode-Counter#1]
I got this error
`Error: Invalid or corrupt jarfile InsnCounter.jar`

How can you help me run your code?

**Comment by lvxiaoxin** [comment]
> I got this error
> `Error: Invalid or corrupt jarfile InsnCounter.jar`
> 
> How can you help me run your code?

I had a try and did not get this error. Could you please show some details of your running environment and how you run it?

By the way, I also found this - [link](https://stackoverflow.com/questions/7559072/corrupt-jar-file), which maybe helpful for you.

**Comment by lvxiaoxin** [comment]
Since no updated got, I will close this issue.
